/**
 * Stili cromatici condivisi per Widget Tier e Widget Buttons.
 * Colori base: bianco, grigio, rosso, nero, ocra, blu, giallo, viola, verde, porpora.
 */

export const CHROMATIC_STYLES = {
  default: {
    name: 'Default',
    gradient: 'from-gray-700 to-gray-800',
    border: 'border-gray-300',
    bg: 'from-gray-50 to-gray-100',
    headerBg: 'bg-gray-800',
    headerText: 'text-white',
    icon: 'bg-gray-600',
    text: 'text-gray-700',
  },
  white: {
    name: 'Bianco',
    gradient: 'from-gray-100 to-white',
    border: 'border-gray-300',
    bg: 'from-white to-gray-50',
    headerBg: 'bg-white',
    headerText: 'text-gray-800',
    icon: 'bg-gray-400',
    text: 'text-gray-700',
  },
  gray: {
    name: 'Grigio',
    gradient: 'from-gray-500 to-gray-600',
    border: 'border-gray-400',
    bg: 'from-gray-100 to-gray-200',
    headerBg: 'bg-gray-600',
    headerText: 'text-white',
    icon: 'bg-gray-500',
    text: 'text-gray-700',
  },
  red: {
    name: 'Rosso',
    gradient: 'from-red-600 to-red-700',
    border: 'border-red-300',
    bg: 'from-red-50 to-red-100',
    headerBg: 'bg-red-700',
    headerText: 'text-white',
    icon: 'bg-red-600',
    text: 'text-red-800',
  },
  black: {
    name: 'Nero',
    gradient: 'from-gray-900 to-black',
    border: 'border-gray-700',
    bg: 'from-gray-800 to-gray-900',
    headerBg: 'bg-black',
    headerText: 'text-white',
    icon: 'bg-gray-800',
    text: 'text-gray-200',
  },
  ochre: {
    name: 'Ocra',
    gradient: 'from-amber-700 to-yellow-800',
    border: 'border-amber-300',
    bg: 'from-amber-50 to-yellow-100',
    headerBg: 'bg-amber-800',
    headerText: 'text-white',
    icon: 'bg-amber-600',
    text: 'text-amber-900',
  },
  blue: {
    name: 'Blu',
    gradient: 'from-blue-600 to-blue-700',
    border: 'border-blue-300',
    bg: 'from-blue-50 to-blue-100',
    headerBg: 'bg-blue-700',
    headerText: 'text-white',
    icon: 'bg-blue-600',
    text: 'text-blue-800',
  },
  yellow: {
    name: 'Giallo',
    gradient: 'from-yellow-500 to-amber-500',
    border: 'border-yellow-300',
    bg: 'from-yellow-50 to-amber-50',
    headerBg: 'bg-yellow-500',
    headerText: 'text-gray-900',
    icon: 'bg-yellow-600',
    text: 'text-yellow-900',
  },
  purple: {
    name: 'Viola',
    gradient: 'from-violet-600 to-purple-700',
    border: 'border-violet-300',
    bg: 'from-violet-50 to-purple-50',
    headerBg: 'bg-violet-700',
    headerText: 'text-white',
    icon: 'bg-violet-600',
    text: 'text-violet-800',
  },
  green: {
    name: 'Verde',
    gradient: 'from-green-600 to-emerald-700',
    border: 'border-green-300',
    bg: 'from-green-50 to-emerald-50',
    headerBg: 'bg-green-700',
    headerText: 'text-white',
    icon: 'bg-green-600',
    text: 'text-green-800',
  },
  porpora: {
    name: 'Porpora',
    gradient: 'from-purple-700 to-fuchsia-700',
    border: 'border-purple-300',
    bg: 'from-purple-50 to-fuchsia-50',
    headerBg: 'bg-purple-800',
    headerText: 'text-white',
    icon: 'bg-purple-600',
    text: 'text-purple-800',
  },
};

// Per i pulsanti: gradienti e stili compatibili con WidgetButtons
export const CHROMATIC_PRESETS_BUTTONS = {
  // Stili cromatici (identici a Tier)
  white: { ...CHROMATIC_STYLES.white },
  gray: { ...CHROMATIC_STYLES.gray },
  red: { ...CHROMATIC_STYLES.red },
  black: { ...CHROMATIC_STYLES.black },
  ochre: { ...CHROMATIC_STYLES.ochre },
  blue: { ...CHROMATIC_STYLES.blue },
  yellow: { ...CHROMATIC_STYLES.yellow },
  purple: { ...CHROMATIC_STYLES.purple },
  green: { ...CHROMATIC_STYLES.green },
  porpora: { ...CHROMATIC_STYLES.porpora },
  // Preset originali per backward compat
  indigo_purple: {
    name: 'Indaco-Viola',
    gradient: 'from-indigo-500 to-purple-600',
    border: 'border-indigo-200',
    bg: 'from-indigo-50 to-purple-50',
    icon: 'bg-indigo-500',
    text: 'text-indigo-500',
  },
  red_orange: {
    name: 'Rosso-Arancio',
    gradient: 'from-red-600 to-orange-600',
    border: 'border-red-200',
    bg: 'from-red-50 to-orange-50',
    icon: 'bg-red-500',
    text: 'text-red-500',
  },
  emerald_teal: {
    name: 'Smeraldo-Verde Acqua',
    gradient: 'from-emerald-500 to-teal-600',
    border: 'border-emerald-200',
    bg: 'from-emerald-50 to-teal-50',
    icon: 'bg-emerald-500',
    text: 'text-emerald-500',
  },
  blue_indigo: {
    name: 'Blu-Indaco',
    gradient: 'from-blue-500 to-indigo-600',
    border: 'border-blue-200',
    bg: 'from-blue-50 to-indigo-50',
    icon: 'bg-blue-500',
    text: 'text-blue-500',
  },
  pink_rose: {
    name: 'Rosa-Rosa Intenso',
    gradient: 'from-pink-500 to-rose-600',
    border: 'border-pink-200',
    bg: 'from-pink-50 to-rose-50',
    icon: 'bg-pink-500',
    text: 'text-pink-500',
  },
  amber_orange: {
    name: 'Ambra-Arancio',
    gradient: 'from-amber-500 to-orange-600',
    border: 'border-amber-200',
    bg: 'from-amber-50 to-orange-50',
    icon: 'bg-amber-500',
    text: 'text-amber-500',
  },
  cyan_blue: {
    name: 'Ciano-Blu',
    gradient: 'from-cyan-500 to-blue-600',
    border: 'border-cyan-200',
    bg: 'from-cyan-50 to-blue-50',
    icon: 'bg-cyan-500',
    text: 'text-cyan-500',
  },
  violet_purple: {
    name: 'Viola-Porpora',
    gradient: 'from-violet-500 to-purple-600',
    border: 'border-violet-200',
    bg: 'from-violet-50 to-purple-50',
    icon: 'bg-violet-500',
    text: 'text-violet-500',
  },
  slate_gray: {
    name: 'Ardesia-Grigio',
    gradient: 'from-slate-600 to-gray-700',
    border: 'border-slate-200',
    bg: 'from-slate-50 to-gray-50',
    icon: 'bg-slate-600',
    text: 'text-slate-600',
  },
  lime_green: {
    name: 'Lime-Verde',
    gradient: 'from-lime-500 to-green-600',
    border: 'border-lime-200',
    bg: 'from-lime-50 to-green-50',
    icon: 'bg-lime-500',
    text: 'text-lime-500',
  },
};
