name: Deploy React App a KOR-35

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Codice
      uses: actions/checkout@v4

    - name: Deploy su Server (Build su Server)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        
        # SCRIPT AGGIORNATO (con sudo)
        script: |
          # 0. Carica il profilo per trovare Node.js (aggiornato)
          # Questo assicura che usi la versione 22.x
          source /etc/profile
          
          # 1. Vai alla cartella del repository sul server
          cd ${{ secrets.REPO_PATH_ON_SERVER }}
          
          # 2. Aggiorna il codice dal repository
          git fetch origin main
          git reset --hard origin/main
          
          # 3. Installa le dipendenze di Node.js
          npm install
          
          # 4. Esegui la build di React
          npm run build
          
          # 5. Svuota la cartella web (con sudo)
          sudo rm -rf ${{ secrets.DEPLOY_TARGET_PATH }}/*
          
          # 6. Copia i file buildati (con sudo)
          sudo cp -R dist/* ${{ secrets.DEPLOY_TARGET_PATH }}/
