name: Deploy React App a KOR-35

# Si attiva ad ogni push sul branch 'main'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Codice
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Usa una versione di Node moderna
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build Progetto React
      # Questo esegue "vite build" come da tuo package.json
      # e crea la cartella 'dist'
      run: npm run build

    - name: Deploy su Server (rsync)
      uses: Burnett-Actions/rsync-deploy@v7
      with:
        # -avzr = archive, verbose, compress, recursive
        # --delete = cancella i file vecchi sul server
        switches: -avzr --delete
        # Percorso sorgente (la cartella 'dist' creata dal build)
        path: "dist/"
        
        # Variabili che arrivano dai Segreti di GitHub
        remote_path: ${{ secrets.DEPLOY_TARGET_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_SSH_KEY }}